name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/Zhangyu-zzzz/cardesignspace-2025-1.git
        cd cardesignspace-2025-1
        
    - name: Setup environment
      run: |
        echo "Setting up deployment environment..."
        
    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # 设置SSH密钥
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        
        # 连接到服务器并部署
        ssh $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /opt/auto-gallery
          echo "Pulling latest code..."
          git pull origin main
          echo "Stopping services..."
          docker-compose down
          echo "Starting services..."
          docker-compose up -d
          echo "Checking service status..."
          docker-compose ps
          echo "Deployment completed!"
        EOF
        
    - name: Health check
      run: |
        echo "Performing health checks..."
        sleep 30
        curl -f http://${{ secrets.SERVER_HOST }}:8080/health || echo "Frontend health check failed"
        curl -f http://${{ secrets.SERVER_HOST }}:3001/api/health || echo "Backend health check failed"
