name: Optimized Docker Build

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build backend image with retry
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile.optimized
        push: false
        tags: auto-gallery-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        
    - name: Build frontend image with retry
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: auto-gallery-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        
    - name: Test images
      run: |
        echo "Testing built images..."
        docker run --rm auto-gallery-backend:latest node --version
        docker run --rm auto-gallery-frontend:latest nginx -v
        echo "Images tested successfully!"
