name: Test Deployment

on:
  workflow_dispatch: # 手动触发

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "=== 测试SSH连接 ==="
        echo "服务器地址: $SERVER_HOST"
        echo "服务器用户: $SERVER_USER"
        
        # 设置SSH密钥
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # 添加服务器到已知主机
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        
        # 测试连接
        echo "测试SSH连接..."
        ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "echo 'SSH连接成功' && whoami && pwd"
        
        echo "=== SSH连接测试完成 ==="
